version: "3"

services:
  web:
    container_name: web
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - db
  
  php:
    container_name: php-fpm
    build: ./php
    restart: always
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7.22
    container_name: banco
    volumes:
      - "./myData:/var/lib/mysql"
    restart: always
    env_file:
      - ".env"
    command: ["--explicit_defaults_for_timestamp"]
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
