version: "3"

services:
  web:
    container_name: web
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - db
  
  php:
    container_name: php-fpm
    build: ./php
    restart: always
    volumes:
      - ./:/var/www

  db:
    container_name: banco
    build: ./mysql
    volumes:
      - "./mysql/db/data:/var/lib/mysql"
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--explicit_defaults_for_timestamp']
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER = ${MYSQL_USER}
      - MYSQL_PASSWORD = ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"